Syncforge Update - 2025-03-03T18:00:19.229Z
Changes:
- changed: gitService.ts
- changed: extension.ts

Code Snippets:

```
gitService.ts:
/* eslint-disable no-unused-vars */
import { Buffer } from 'buffer';
import * as vscode from 'vscode';
import simpleGit, { SimpleGit, SimpleGitOptions } from 'simple-git';
import * as path from 'path';
import { EventEmitter } from 'events';
import { OutputChannel } from 'vscode';
import { promisify } from 'util';
import { exec } from 'child_process';
import { execSync } from 'child_process';
import process from 'process';
const execAsync = promisify(exec);
import * as fs from 'fs';
import { fileURLToPath } from 'url';

interface TimeDistribution {
  hour: number;
  changes: number;
}

interface ActivityTimelineEntry {
  date: string;
  commits: number;
  filesChanged: number;
}

interface FileTypeStats {
  name: string;
  count: number;
  percentage: number;
}

interface DevTrackStats {
  totalTime: number;
  filesModified: number;
  totalCommits: number;
  linesChanged: number;
  activityTimeline: ActivityTimelineEntry[];
  timeDistribution: TimeDistribution[];
  fileTypes: FileTypeStats[];
}

interface GitServiceEvents {
  commit: (message: string) => void;
  error: (error: Error) => void;
  'operation:start': (operation: string) => void;
  'operation:end': (operation: string) => void;
  retry: (operation: string, attempt: number) => void;
  push: (branch: string) => void;
}
... (truncated for brevity)
```

```
extension.ts:
/* eslint-disable no-unused-vars */
import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { execSync } from 'child_process';
import { Buffer } from 'node:buffer';
import { GitHubService } from './services/githubService';
import { GitService } from './services/gitService';
import { Tracker } from './services/tracker';
import { SummaryGenerator } from './services/summaryGenerator';
import { Scheduler } from './services/scheduler';
import { ChangeAnalyzer } from './services/changeAnalyzer';
import { platform, homedir } from 'os';

// Interfaces
interface PersistedAuthState {
  username?: string;
  repoName?: string;
  lastWorkspace?: string;
}

interface DevTrackServices {
  outputChannel: vscode.OutputChannel;
  githubService: GitHubService;
  gitService: GitService;
  tracker: Tracker;
  summaryGenerator: SummaryGenerator;
  scheduler: Scheduler | null;
  trackingStatusBar: vscode.StatusBarItem;
  authStatusBar: vscode.StatusBarItem;
  extensionContext: vscode.ExtensionContext;
  changeAnalyzer: ChangeAnalyzer;
}

// Git Installation Handler
class GitInstallationHandler {
  private static readonly DOWNLOAD_URLS = {
    win32: 'https://git-scm.com/download/win',
    darwin: 'https://git-scm.com/download/mac',
    linux: 'https://git-scm.com/download/linux',
  };

  static async checkGitInstallation(
    outputChannel: vscode.OutputChannel
  ): Promise<boolean> {
    try {
      const gitVersion = execSync('git --version', { encoding: 'utf8' });
      outputChannel.appendLine(`DevTrack: Git found - ${gitVersion.trim()}`);
      return true;
    } catch {
... (truncated for brevity)
```